### ISSUE TITLE
Linux Web service aborted

### ISSUE THREAD

**Issue by mufaka** [mufaka/KronoMata#3]
This happened when updating a ScheduledJob to run on 'All' hosts.

	sudo systemctl status KronoMata.Web

	● KronoMata.Web.service - KronoMata Web Application
		 Loaded: loaded (/etc/systemd/system/KronoMata.Web.service; disabled; vendor preset: enabled)
		 Active: failed (Result: signal) since Fri 2023-08-25 10:01:12 PDT; 55s ago
		Process: 128935 ExecStart=/usr/bin/dotnet /home/bnickel/KronoMata/Publish/Web/KronoMata.Web.dll (code=killed, signal=ABRT)
	   Main PID: 128935 (code=killed, signal=ABRT)

The ScheduledJob table in SQLite has a Not Null constraint and that exception is not being handled gracefully.

	sudo journalctl -e -u KronoMata.Web.service
   
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]: code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x87AF202F): constraint failed
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]: NOT NULL constraint failed: ScheduledJob.HostId
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Data.SQLite.SQLiteDataReader.NextResult()
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]: --- End of stack trace from previous location ---
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in /_/Dapper/SqlMapper.Async.cs:line 655
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at KronoMata.Data.SQLite.SQLiteScheduledJobDataStore.<>c__DisplayClass6_0.<<Update>b__0>d.MoveNext() in D:\Development\KronoMata\KronoMata.Data.SQLite\SQLiteScheduledJobDataS>
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]: --- End of stack trace from previous location ---
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Threading.QueueUserWorkItemCallback.Execute()
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
	Aug 25 10:01:02 flash3r KronoMataWeb[128935]:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
	Aug 25 10:01:12 flash3r systemd[1]: KronoMata.Web.service: Main process exited, code=killed, status=6/ABRT
	Aug 25 10:01:12 flash3r systemd[1]: KronoMata.Web.service: Failed with result 'signal'.

**Comment by mufaka** [comment]
This issue was two fold. HostId wasn't nullable in database and async calls that throw unhandled exceptions cause a app crashes. HostId is now nullable and async calls replaced until it becomes a performance issue and a good exception handling strategy is found for async calls.
